<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Province</name>
   <tag></tag>
   <elementGuidId>cb60acea-40c7-45bd-9394-6194df386686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ADDRESS_PROVINCE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ADDRESS_PROVINCE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ADDRESS_PROVINCE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Select Province
                                                                                             กระบี่ 
                                                                                             กรุงเทพมหานคร 
                                                                                             กาญจนบุรี 
                                                                                             กาฬสินธุ์ 
                                                                                             กำแพงเพชร 
                                                                                             ขอนแก่น 
                                                                                             จันทบุรี 
                                                                                             ฉะเชิงเทรา 
                                                                                             ชลบุรี 
                                                                                             ชัยนาท 
                                                                                             ชัยภูมิ 
                                                                                             ชุมพร 
                                                                                             ตรัง 
                                                                                             ตราด 
                                                                                             ตาก 
                                                                                             นครนายก 
                                                                                             นครปฐม 
                                                                                             นครพนม 
                                                                                             นครราชสีมา 
                                                                                             นครศรีธรรมราช 
                                                                                             นครสวรรค์ 
                                                                                             นนทบุรี 
                                                                                             นราธิวาส 
                                                                                             น่าน 
                                                                                             บึงกาฬ 
                                                                                             บุรีรัมย์ 
                                                                                             ปทุมธานี 
                                                                                             ประจวบคีรีขันธ์ 
                                                                                             ปราจีนบุรี 
                                                                                             ปัตตานี 
                                                                                             พระนครศรีอยุธยา 
                                                                                             พะเยา 
                                                                                             พังงา 
                                                                                             พัทลุง 
                                                                                             พิจิตร 
                                                                                             พิษณุโลก 
                                                                                             ภูเก็ต 
                                                                                             มหาสารคาม 
                                                                                             มุกดาหาร 
                                                                                             ยะลา 
                                                                                             ยโสธร 
                                                                                             ระนอง 
                                                                                             ระยอง 
                                                                                             ราชบุรี 
                                                                                             ร้อยเอ็ด 
                                                                                             ลพบุรี 
                                                                                             ลำปาง 
                                                                                             ลำพูน 
                                                                                             ศรีสะเกษ 
                                                                                             สกลนคร 
                                                                                             สงขลา 
                                                                                             สตูล 
                                                                                             สมุทรปราการ 
                                                                                             สมุทรสงคราม 
                                                                                             สมุทรสาคร 
                                                                                             สระบุรี 
                                                                                             สระแก้ว 
                                                                                             สิงห์บุรี 
                                                                                             สุพรรณบุรี 
                                                                                             สุราษฎร์ธานี 
                                                                                             สุรินทร์ 
                                                                                             สุโขทัย 
                                                                                             หนองคาย 
                                                                                             หนองบัวลำภู 
                                                                                             อำนาจเจริญ 
                                                                                             อุดรธานี 
                                                                                             อุตรดิตถ์ 
                                                                                             อุทัยธานี 
                                                                                             อุบลราชธานี 
                                                                                             อ่างทอง 
                                                                                             เชียงราย 
                                                                                             เชียงใหม่ 
                                                                                             เพชรบุรี 
                                                                                             เพชรบูรณ์ 
                                                                                             เลย 
                                                                                             แพร่ 
                                                                                             แม่ฮ่องสอน 
                                                                                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ADDRESS_PROVINCE&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='ADDRESS_PROVINCE']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/div/div/div/div/div/form/div[2]/div[11]/div[2]/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='จังหวัด/Province :'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ถนน/Road :'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='อำเภอ/District :'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ตำบล/Sub-district :'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
